def foo1 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo2 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo3 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo4 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo5 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo6 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo7 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo8 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo9 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo10 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo11 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo12 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo13 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo14 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo15 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo16 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo17 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo18 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo19 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo20 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo21 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo22 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo23 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo24 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo25 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo26 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo27 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo28 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo29 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo30 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo31 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo32 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo33 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo34 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo35 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo36 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo37 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo38 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo39 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo40 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo41 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo42 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo43 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo44 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo45 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo46 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo47 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo48 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo49 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo50 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo51 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo52 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo53 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo54 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo55 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo56 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo57 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo58 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo59 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo60 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo61 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo62 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo63 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo64 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo65 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo66 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo67 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo68 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo69 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo70 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo71 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo72 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo73 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo74 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo75 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo76 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo77 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo78 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo79 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo80 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo81 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo82 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo83 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo84 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo85 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo86 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo87 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo88 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo89 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo90 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo91 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo92 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo93 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo94 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo95 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo96 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo97 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo98 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo99 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
def foo100 [x y: int, z: list<list<int>> ] { [ $x $y, $z ] }
